name: "Validate"
on:
  pull_request:
  push:
    branches:
      - master

env:
  REQUIRED_PHP_EXTENSIONS: mbstring, mysqli, pdo_sqlite

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        laravel-version:
          - "^10"
          - "^11"
          - "^12"
          - "^13"

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          extensions: ${{ env.REQUIRED_PHP_EXTENSIONS }}
          php-version: ${{ matrix.php-version }}

      - run: composer require illuminate/support:${{ matrix.laravel-version }} --no-interaction --prefer-dist --no-progress

      - run: vendor/bin/phpunit

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: ${{ env.REQUIRED_PHP_EXTENSIONS }}
          php-version: 8.3

      - uses: ramsey/composer-install@v3

      - run: vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-filter=src

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
